/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"

#include "StdH.h"
#include "EntitiesMP/WorldSettingsController.h"
#include "EntitiesMP/BackgroundViewer.h"

#include <HudPicHolder.h>
#include <HudPicHolder_tables.h>
#line 9 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"

BOOL _bDataLoaded = FALSE;
BOOL _bDataError = FALSE;
CTextureObject _toTexture;

void CHudPicHolder::SetDefaultProperties(void) {
	m_strName = "Hud pic holder";
	m_strDescription = "";
	m_fnmPicture = CTString("");
	m_tmFadeInStart = 1e6;
	m_tmFadeOutStart = 1e6;
	m_tmFadeInLen = 0.5f;
	m_tmFadeOutLen = 0.5f;
	m_tmAutoFadeOut = -1.0f;
	m_fYRatio = 0.5f;
	m_fXRatio = 0.5f;
	m_fPictureStretch = 1.0f;
	CRationalEntity::SetDefaultProperties();
}

#line 39 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
const CTString & CHudPicHolder::GetDescription(void)const {
#line 40 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
((CTString &) m_strDescription ) . PrintF  ("%s" , m_fnmPicture  . FileName  ());
#line 41 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return m_strDescription ;
#line 42 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}

#line 44 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
BOOL CHudPicHolder::ReloadData(void) 
#line 45 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 46 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
_bDataError  = FALSE ;
#line 47 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(! Picture_On  (m_fnmPicture ))
#line 48 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 49 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
Picture_Off  ();
#line 50 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return FALSE ;
#line 51 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}
#line 52 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return TRUE ;
#line 53 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}

#line 55 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
BOOL CHudPicHolder::LoadOneFile(const CTFileName & fnm) 
#line 56 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 57 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(fnm  == ""){return FALSE ;}
#line 58 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
try 
#line 59 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 60 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
_toTexture  . SetData_t  (fnm );
#line 61 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return TRUE ;
#line 62 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}
#line 63 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
catch  (char  * strError )
#line 64 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 65 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
CPrintF  ("%s\n" , strError );
#line 66 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return FALSE ;
#line 67 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}
#line 68 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}

#line 71 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
BOOL CHudPicHolder::Picture_On(CTFileName fnPic) 
#line 72 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 73 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return LoadOneFile  (fnPic );
#line 74 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}

#line 77 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
void CHudPicHolder::Picture_Off(void) 
#line 78 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 79 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
_toTexture  . SetData  (NULL );
#line 80 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}

#line 83 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
FLOAT CHudPicHolder::HudPic_Render(CHudPicHolder * penThis,CDrawPort * pdp) 
#line 84 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 85 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(_bDataError ){return 0;}
#line 87 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(! _bDataLoaded ){
#line 88 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(! ReloadData  ()){
#line 89 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
_bDataError  = TRUE ;
#line 90 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return 0;
#line 91 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}
#line 92 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
_bDataLoaded  = TRUE ;
#line 93 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return 1;
#line 94 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}
#line 96 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
FLOAT fNow  = _pTimer  -> CurrentTick  ();
#line 97 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(fNow  < m_tmFadeInStart ){return 0;}
#line 98 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(fNow  > m_tmFadeOutStart  + m_tmFadeOutLen ){return 0;}
#line 100 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
CDrawPort  * pdpCurr  = pdp ;
#line 101 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
pdpCurr  -> SetAsCurrent  ();
#line 103 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
FLOAT fRatio  = 1.0f;
#line 104 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(fNow  > m_tmFadeOutStart )
#line 105 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 106 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
fRatio  = CalculateRatio  (fNow  , m_tmFadeOutStart  , m_tmFadeOutStart  + m_tmFadeOutLen  , 0 , 1);
#line 107 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}
#line 108 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(fNow  < m_tmFadeInStart  + m_tmFadeInLen )
#line 109 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 110 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
fRatio  = CalculateRatio  (fNow  , m_tmFadeInStart  , m_tmFadeInStart  + m_tmFadeInLen  , 1 , 0);
#line 111 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}
#line 112 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
UBYTE  ubA  = ClampUp  (UBYTE  (fRatio  * 255.0f) , UBYTE  (255));
#line 114 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
CTextureData  * ptd  = (CTextureData  *) _toTexture  . GetData  ();
#line 116 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
FLOAT fResScale  = (FLOAT) pdpCurr  -> GetHeight  () / 480.0f;
#line 117 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
const MEX  mexTexW  = ptd  -> GetWidth  ();
#line 118 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
const MEX  mexTexH  = ptd  -> GetHeight  ();
#line 119 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
FLOAT fPicRatioW  , fPicRatioH ;
#line 120 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(mexTexW  > mexTexH ){
#line 121 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
fPicRatioW  = mexTexW  / mexTexH ;
#line 122 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
fPicRatioH  = 1.0f;
#line 123 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}else {
#line 124 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
fPicRatioW  = 1.0f;
#line 125 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
fPicRatioH  = mexTexH  / mexTexW ;
#line 126 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}
#line 127 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
PIX  picW  = 128 * m_fPictureStretch  * fResScale  * fPicRatioW ;
#line 128 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
PIX  picH  = 128 * m_fPictureStretch  * fResScale  * fPicRatioH ;
#line 130 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
FLOAT fXCenter  = m_fXRatio  * pdpCurr  -> GetWidth  ();
#line 131 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
FLOAT fYCenter  = m_fYRatio  * pdpCurr  -> GetHeight  ();
#line 132 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
PIXaabbox2D  boxScr  = PIXaabbox2D  (
#line 133 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
PIX2D  (fXCenter  - picW  / 2 , fYCenter  - picH  / 2) , 
#line 134 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
PIX2D  (fXCenter  + picW  / 2 , fYCenter  + picH  / 2));
#line 135 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
pdpCurr  -> PutTexture  (& _toTexture  , boxScr  , C_WHITE  | ubA );
#line 137 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
pdp  -> SetAsCurrent  ();
#line 139 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return 1;
#line 140 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}
BOOL CHudPicHolder::
#line 144 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CHudPicHolder_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CHudPicHolder::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 146 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
InitAsEditorModel  ();
#line 147 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 148 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 151 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
SetModel  (MODEL_MARKER );
#line 152 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
SetModelMainTexture  (TEXTURE_MARKER );
#line 154 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
SetTimerAfter(0.05f);
Jump(STATE_CURRENT, 0x00f10000, FALSE, EBegin());return TRUE;}BOOL CHudPicHolder::H0x00f10000_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f10000
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x00f10001, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CHudPicHolder::H0x00f10001_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f10001
;
#line 156 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(! Picture_On  (m_fnmPicture ))
#line 157 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 158 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
Picture_Off  ();
#line 159 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
Return(STATE_CURRENT,EVoid());
#line 159 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return TRUE;
#line 160 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}
#line 161 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
_bDataError  = FALSE ;
#line 163 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x00f10002, FALSE, EBegin());return TRUE;}BOOL CHudPicHolder::H0x00f10002_Main_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f10002
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):
#line 165 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{const EBegin&e= (EBegin&)__eeInput;

#line 166 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return TRUE;
#line 167 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStart):
#line 169 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{const EStart&eStart= (EStart&)__eeInput;

#line 170 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
CWorldSettingsController  * pwsc  = GetWSC  (this );
#line 171 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(pwsc  != NULL )
#line 172 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 173 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
m_tmFadeInStart  = _pTimer  -> CurrentTick  ();
#line 174 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
EHudPicFX  etfx ;
#line 175 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
etfx  . bStart  = TRUE ;
#line 176 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
etfx  . penSender  = this ;
#line 177 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
pwsc  -> SendEvent  (etfx );
#line 178 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(m_tmAutoFadeOut  != - 1)
#line 179 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{
#line 180 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
Call(STATE_CURRENT, STATE_CHudPicHolder_WaitAndFadeOut, TRUE, EVoid());return TRUE;
#line 181 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}
#line 182 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}
#line 183 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return TRUE;
#line 184 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):
#line 186 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{const EStop&eStop= (EStop&)__eeInput;

#line 187 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
Call(STATE_CURRENT, STATE_CHudPicHolder_ApplyFadeOut, TRUE, EVoid());return TRUE;
#line 188 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return TRUE;
#line 189 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}ASSERT(FALSE);break;case(EVENTCODE_EReturn):
#line 191 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
{const EReturn&e= (EReturn&)__eeInput;

#line 192 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return TRUE;
#line 193 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 194 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
}return TRUE;}BOOL CHudPicHolder::H0x00f10003_Main_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f10003

#line 195 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
Picture_Off  ();
#line 196 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
Return(STATE_CURRENT,EVoid());
#line 196 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CHudPicHolder::
#line 199 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
WaitAndFadeOut(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CHudPicHolder_WaitAndFadeOut
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CHudPicHolder::WaitAndFadeOut expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 201 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
SetTimerAfter(m_tmAutoFadeOut );
Jump(STATE_CURRENT, 0x00f10005, FALSE, EBegin());return TRUE;}BOOL CHudPicHolder::H0x00f10005_WaitAndFadeOut_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f10005
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x00f10006, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CHudPicHolder::H0x00f10006_WaitAndFadeOut_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f10006
;
#line 202 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
Jump(STATE_CURRENT, STATE_CHudPicHolder_ApplyFadeOut, TRUE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CHudPicHolder::
#line 205 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
ApplyFadeOut(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CHudPicHolder_ApplyFadeOut
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CHudPicHolder::ApplyFadeOut expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 207 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
m_tmFadeOutStart  = _pTimer  -> CurrentTick  ();
#line 208 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
CWorldSettingsController  * pwsc  = GetWSC  (this );
#line 209 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
if(!(pwsc  != NULL )){ Jump(STATE_CURRENT,0x00f1000a, FALSE, EInternal());return TRUE;}
#line 211 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
SetTimerAfter(m_tmFadeOutLen );
Jump(STATE_CURRENT, 0x00f10008, FALSE, EBegin());return TRUE;}BOOL CHudPicHolder::H0x00f10008_ApplyFadeOut_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f10008
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x00f10009, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CHudPicHolder::H0x00f10009_ApplyFadeOut_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f10009
;
#line 212 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
CWorldSettingsController  * pwsc  = GetWSC  (this );
#line 213 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
ETextFX  etfx ;
#line 214 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
etfx  . bStart  = FALSE ;
#line 215 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
etfx  . penSender  = this ;
#line 216 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
pwsc  -> SendEvent  (etfx );Jump(STATE_CURRENT,0x00f1000a, FALSE, EInternal());return TRUE;}BOOL CHudPicHolder::H0x00f1000a_ApplyFadeOut_03(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00f1000a

#line 218 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
Return(STATE_CURRENT,EReturn  ());
#line 218 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/HudPicHolder.es"
return TRUE; ASSERT(FALSE); return TRUE;};