/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"

#include "StdH.h"

#include <Light.h>
#include <Light_tables.h>
#line 33 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"


void CLight_OnInitClass(void)
{
	// init lens flares effects
	InitLensFlares();
}

void CLight_OnEndClass(void)
{
	// close lens flares effects
	CloseLensFlares();
}


void CLight::SetDefaultProperties(void) {
	m_colColor = C_GRAY ;
	m_colAmbient = C_BLACK ;
	m_fAmbientAttenuation = 0.0f;
	m_rFallOffRange = 8.0f;
	m_rHotSpotRange = 0.0f;
	m_itIllumination = 0;
	m_ltType = LT_POINT ;
	m_strDescription = "";
	m_strName = "Light";
	m_bDarkLight = FALSE ;
	m_fNearClip = 0.1f;
	m_fFarClip = 0.01f;
	m_bSubstractSectorAmbient = FALSE ;
	m_bRenderAsSmallLight = FALSE ;
	m_lftLensFlare = LFT_NONE ;
	m_bBackground = FALSE ;
	m_bLensFlareOnly = FALSE ;
	m_fnmLightAnimation = CTString("");
	m_iLightAnimation = 0;
	m_tmOffsetPhase = 0.0f;
	m_tmAniStartTime = 0.0f;
	m_fTimeMultiply = 1.0f;
	m_aoLightAnimation.SetData(NULL);

	m_bTargetable = FALSE ;
	m_bDynamic = FALSE ;
	m_bDiffusion = TRUE ;
	m_fnmAmbientLightAnimation = CTString("");
	m_iAmbientLightAnimation = 0;
	m_aoAmbientLightAnimation.SetData(NULL);

	CEntity::SetDefaultProperties();
}

#line 99 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
void CLight::Read_t(CTStream * istr,BOOL bNetwork) 
#line 100 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 101 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(bNetwork ){
#line 102 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_bdfInitialized  . bdf_bValue  = FALSE ;
#line 103 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 105 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_bdfInitialized  . bdf_bValue  = FALSE ;
#line 106 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_plsLight  = GetLightSource  ();
#line 107 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_bdfInitialized  . bdf_bValue  = FALSE ;
#line 109 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
CEntity  :: Read_t  (istr  , bNetwork );
#line 110 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}

#line 113 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
CAnimData * CLight::GetAnimData(SLONG slPropertyOffset) 
#line 114 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 115 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(slPropertyOffset  == offsetof  (CLight  , m_iLightAnimation ))
#line 116 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 117 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
return m_aoLightAnimation  . GetData  ();
#line 118 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 119 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
else if(slPropertyOffset  == offsetof  (CLight  , m_iAmbientLightAnimation ))
#line 120 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 121 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
return m_aoAmbientLightAnimation  . GetData  ();
#line 122 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 123 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
else 
#line 124 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 125 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
return CEntity  :: GetAnimData  (slPropertyOffset );
#line 126 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 127 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}

#line 129 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
BOOL CLight::IsTargetable(void)const 
#line 130 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 131 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
return m_bTargetable ;
#line 132 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}

#line 134 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
BOOL CLight::IsImportant(void)const 
#line 135 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 136 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
return (m_ltType  == LT_DIRECTIONAL );
#line 137 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}

#line 140 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
BOOL CLight::HandleEvent(const CEntityEvent & ee) 
#line 141 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 143 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(ee  . ee_slEvent  == EVENTCODE_ERangeModelDestruction )
#line 144 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 145 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetFlagOn  (ENF_PROPSCHANGED );
#line 147 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_colColor  = C_BLACK ;
#line 148 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_colAmbient  = C_BLACK ;
#line 149 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
CLightSource  lsNew ;
#line 150 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetupLightSource  (lsNew );
#line 151 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSource  (lsNew );
#line 152 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
return TRUE ;
#line 154 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 155 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
else if(ee  . ee_slEvent  == EVENTCODE_EChangeAnim )
#line 156 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 157 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetFlagOn  (ENF_PROPSCHANGED );
#line 158 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
EChangeAnim  & eChange  = (EChangeAnim  &) ee ;
#line 161 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_iLightAnimation  = eChange  . iLightAnim ;
#line 162 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_aoLightAnimation  . GetData  () != NULL )
#line 163 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 164 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_aoLightAnimation  . PlayAnim  (m_iLightAnimation  , eChange  . bLightLoop  ? AOF_LOOPING  : 0);
#line 165 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 168 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_iAmbientLightAnimation  = eChange  . iAmbientLightAnim ;
#line 169 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_aoAmbientLightAnimation  . GetData  () != NULL )
#line 170 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 171 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_aoAmbientLightAnimation  . PlayAnim  (m_iAmbientLightAnimation  , eChange  . bAmbientLightLoop  ? AOF_LOOPING  : 0);
#line 172 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 175 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if((m_aoLightAnimation  . GetData  () == NULL ) && (m_aoAmbientLightAnimation  . GetData  () == NULL ))
#line 176 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 177 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_colColor  = eChange  . colDiffuse ;
#line 178 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_colAmbient  = eChange  . colAmbient ;
#line 179 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
CLightSource  lsNew ;
#line 180 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetupLightSource  (lsNew );
#line 181 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSource  (lsNew );
#line 182 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 183 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
return TRUE ;
#line 184 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 185 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
return FALSE ;
#line 186 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}

#line 189 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
void CLight::MirrorAndStretch(FLOAT fStretch,BOOL bMirrorX) 
#line 190 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 192 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_rFallOffRange  *= fStretch ;
#line 193 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_rHotSpotRange  *= fStretch ;
#line 194 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_fNearClip  *= fStretch ;
#line 195 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_fFarClip  *= fStretch ;
#line 197 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}

#line 200 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
CLightSource * CLight::GetLightSource(void) 
#line 201 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 203 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(! m_bdfInitialized  . bdf_bValue ){
#line 205 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
CLightSource  lsNew ;
#line 206 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetupLightSource  (lsNew );
#line 207 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSourceWithNoDiscarding  (lsNew );
#line 208 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_bdfInitialized  . bdf_bValue  = TRUE ;
#line 209 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 210 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
return & m_lsLightSource ;
#line 211 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}

#line 214 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
void CLight::SetupLightSource(CLightSource & lsNew) 
#line 215 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 216 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
switch(m_ltType ){
#line 217 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LT_POINT : 
#line 218 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LT_STRONG_POINT : 
#line 219 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  = LSF_CASTSHADOWS ;
#line 220 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 221 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LT_DIRECTIONAL : 
#line 222 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  = LSF_DIRECTIONAL  | LSF_CASTSHADOWS ;
#line 223 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 224 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LT_STRONG_AMBIENT : 
#line 225 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LT_AMBIENT : 
#line 226 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  = 0;
#line 227 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 228 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 229 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_bSubstractSectorAmbient ){lsNew  . ls_ulFlags  |= LSF_SUBSTRACTSECTORAMBIENT ;}
#line 230 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_bLensFlareOnly ){lsNew  . ls_ulFlags  |= LSF_LENSFLAREONLY ;}
#line 231 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_bDynamic ){lsNew  . ls_ulFlags  |= LSF_DYNAMIC ;}
#line 233 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_bDarkLight ){
#line 234 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_ltType  == LT_DIRECTIONAL ){
#line 235 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  &= ~ LSF_DARKLIGHT ;
#line 236 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_bDarkLight  = FALSE ;
#line 237 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}else {
#line 238 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  |= LSF_DARKLIGHT ;
#line 239 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 240 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 242 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_bDiffusion ){
#line 243 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_bDynamic  || m_ltType  == LT_AMBIENT  || m_ltType  == LT_STRONG_AMBIENT ){
#line 244 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  &= ~ LSF_DIFFUSION ;
#line 245 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_bDiffusion  = FALSE ;
#line 246 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}else {
#line 247 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  |= LSF_DIFFUSION ;
#line 248 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 249 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 251 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_rHotSpot  = m_rHotSpotRange ;
#line 252 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_rFallOff  = m_rFallOffRange ;
#line 253 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_fNearClipDistance  = m_fNearClip ;
#line 254 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_fFarClipDistance  = m_fFarClip ;
#line 256 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_ltType  == LT_STRONG_AMBIENT  || m_ltType  == LT_STRONG_POINT ){
#line 257 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_rHotSpot  = lsNew  . ls_rFallOff  * 0.9f;
#line 258 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 260 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_colColor  = m_colColor ;
#line 263 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_colAmbient  = m_colAmbient ;
#line 265 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(lsNew  . ls_ulFlags  & LSF_DIRECTIONAL ){
#line 266 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_colAmbient  = m_colAmbient ;
#line 267 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_fAmbientAttenuation  = m_fAmbientAttenuation ;
#line 268 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 269 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_ubPolygonalMask  = (UBYTE ) m_itIllumination ;
#line 271 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
switch(m_lftLensFlare )
#line 272 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 273 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LFT_NONE : 
#line 274 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = NULL ;
#line 275 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 276 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LFT_STANDARD : 
#line 277 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftStandard ;
#line 278 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 279 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LFT_STANDARD_REFLECTIONS : 
#line 280 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftStandardReflections ;
#line 281 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 282 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LFT_YELLOW_STAR_RED_RING : 
#line 283 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftYellowStarRedRing ;
#line 284 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 285 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_STAR_RED_RING : 
#line 286 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStarRedRing ;
#line 287 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 288 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_STAR : 
#line 289 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStar ;
#line 290 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 291 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_STAR_RED_RING_STREAKS : 
#line 292 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteStarRedRingStreaks ;
#line 293 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 294 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_STAR_RED_REFLECTIONS : 
#line 295 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteStarRedReflections ;
#line 296 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 297 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LFT_BLUE_STAR_BLUE_REFLECTIONS : 
#line 298 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftBlueStarBlueReflections ;
#line 299 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 303 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_STAR_RED_RING_FAR : 
#line 304 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftYellowStarRedRingFar ;
#line 305 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 306 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_FAR : 
#line 307 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowFar ;
#line 308 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 309 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_STAR_NG : 
#line 310 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStarNG ;
#line 311 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
break ;
#line 312 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 316 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_paoLightAnimation  = NULL ;
#line 317 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_aoLightAnimation  . GetData  () != NULL ){
#line 318 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_paoLightAnimation  = & m_aoLightAnimation ;
#line 319 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 322 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_paoAmbientLightAnimation  = NULL ;
#line 323 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_aoAmbientLightAnimation  . GetData  () != NULL ){
#line 324 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
lsNew  . ls_paoAmbientLightAnimation  = & m_aoAmbientLightAnimation ;
#line 325 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 326 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}

#line 330 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SLONG CLight::GetUsedMemory(void) 
#line 331 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 333 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SLONG  slUsedMemory  = sizeof  (CLight ) - sizeof  (CEntity ) + CEntity  :: GetUsedMemory  ();
#line 335 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
slUsedMemory  += m_strDescription  . Length  ();
#line 336 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
slUsedMemory  += m_strName  . Length  ();
#line 337 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
slUsedMemory  += m_fnmLightAnimation  . Length  ();
#line 338 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
slUsedMemory  += m_fnmAmbientLightAnimation  . Length  ();
#line 339 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
slUsedMemory  += 2 * sizeof  (CAnimObject);
#line 340 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
return slUsedMemory ;
#line 341 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
BOOL CLight::
#line 345 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CLight_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CLight::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 347 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetFlagOn  (ENF_MARKDESTROY );
#line 348 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetFlagOn  (ENF_NONETCONNECT );
#line 349 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetFlagOff  (ENF_PROPSCHANGED );
#line 352 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_rFallOffRange  < 0){
#line 353 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_rFallOffRange  = 0.0f;
#line 354 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 355 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_rHotSpotRange  < 0){
#line 356 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_rHotSpotRange  = 0.0f;
#line 357 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 359 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_rHotSpotRange  > m_rFallOffRange ){
#line 360 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_rHotSpotRange  = m_rFallOffRange ;
#line 361 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 370 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_fNearClip  <= 0.01f){
#line 371 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_fNearClip  = 0.01f;
#line 372 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 374 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_fFarClip  <= 0){
#line 375 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_fFarClip  = 0.0f;
#line 376 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 379 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_ltType  != LT_DIRECTIONAL ){
#line 383 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_fAmbientAttenuation  = 0.0f;
#line 384 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}else {
#line 385 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_fAmbientAttenuation  = Clamp  (m_fAmbientAttenuation  , 0.0f , 1.0f);
#line 386 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 388 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
InitAsEditorModel  ();
#line 389 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 390 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 393 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_bRenderAsSmallLight )
#line 394 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 395 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
GetModelObject  () -> mo_Stretch  = FLOAT3D (0.25f , 0.25f , 0.25f);
#line 396 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 397 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
else 
#line 398 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 400 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_ltType  != LT_DIRECTIONAL ){
#line 401 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
const float  LIGHT_MINSIZE  = 0.5f;
#line 402 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
FLOAT fFactor  = Log2  (m_rFallOffRange ) * LIGHT_MINSIZE ;
#line 403 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(fFactor  < LIGHT_MINSIZE ){
#line 404 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
fFactor  = LIGHT_MINSIZE ;
#line 405 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 406 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
GetModelObject  () -> mo_Stretch  = FLOAT3D (fFactor  , fFactor  , fFactor );
#line 407 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 408 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 410 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
CTString strType ;
#line 411 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_ltType  == LT_POINT  || m_ltType  == LT_STRONG_POINT )
#line 412 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 413 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
strType  = "point";
#line 415 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetModel  (MODEL_LIGHT_SOURCE );
#line 417 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetModelMainTexture  (TEXTURE_POINT_LIGHT );
#line 418 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 420 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
else if(m_ltType  == LT_AMBIENT )
#line 421 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 422 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
strType  = "ambient";
#line 424 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetModel  (MODEL_LIGHT_SOURCE );
#line 426 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetModelMainTexture  (TEXTURE_AMBIENT_LIGHT );
#line 427 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 429 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
else if(m_ltType  == LT_STRONG_AMBIENT )
#line 430 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 431 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
strType  = "ambient";
#line 433 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetModel  (MODEL_LIGHT_SOURCE );
#line 435 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetModelMainTexture  (TEXTURE_REAL_AMBIENT_LIGHT );
#line 436 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 438 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
else if(m_ltType  == LT_DIRECTIONAL )
#line 439 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 440 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
strType  = "directional";
#line 442 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetModel  (MODEL_SPOT_LIGHT );
#line 444 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetModelMainTexture  (TEXTURE_SPOT_LIGHT );
#line 445 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 447 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_bDarkLight )
#line 448 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
{
#line 449 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
strType  = strType  + ", dark";
#line 450 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 453 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
try {
#line 454 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_aoLightAnimation  . SetData_t  (m_fnmLightAnimation );
#line 455 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}catch  (char  * strError ){
#line 456 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
WarningMessage  (TRANS  ("Cannot load '%s': %s") , (CTString &) m_fnmLightAnimation  , strError );
#line 457 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_fnmLightAnimation  = "";
#line 458 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 459 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_aoLightAnimation  . GetData  () != NULL ){
#line 461 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_aoLightAnimation  . PlayAnim  (m_iLightAnimation  , AOF_LOOPING );
#line 462 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_aoLightAnimation  . ao_tmAnimStart  = - m_tmAniStartTime ;
#line 464 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 467 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
try {
#line 468 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_aoAmbientLightAnimation  . SetData_t  (m_fnmAmbientLightAnimation );
#line 469 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}catch  (char  * strError ){
#line 470 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
WarningMessage  (TRANS  ("Cannot load '%s': %s") , (CTString &) m_fnmAmbientLightAnimation  , strError );
#line 471 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_fnmAmbientLightAnimation  = "";
#line 472 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 473 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_aoAmbientLightAnimation  . GetData  () != NULL ){
#line 475 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_aoAmbientLightAnimation  . PlayAnim  (m_iAmbientLightAnimation  , AOF_LOOPING );
#line 476 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_aoAmbientLightAnimation  . ao_tmAnimStart  = - m_tmAniStartTime ;
#line 478 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 481 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
CLightSource  lsNew ;
#line 482 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetupLightSource  (lsNew );
#line 485 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(m_bBackground ){
#line 486 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetFlags  (GetFlags  () | ENF_BACKGROUND );
#line 487 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}else {
#line 488 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
SetFlags  (GetFlags  () & ~ ENF_BACKGROUND );
#line 489 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 492 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_lsLightSource  . ls_penEntity  = this ;
#line 493 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
if(! m_bdfInitialized  . bdf_bValue ){
#line 494 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSourceWithNoDiscarding  (lsNew );
#line 495 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_bdfInitialized  . bdf_bValue  = TRUE ;
#line 496 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}else {
#line 497 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSource  (lsNew );
#line 498 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
}
#line 501 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_plsLight  = & m_lsLightSource ;
#line 503 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
m_strDescription  . PrintF  ("%s:%g-%g" , 
#line 504 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
strType  , m_rHotSpotRange  , m_rFallOffRange );
#line 506 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
Return(STATE_CURRENT,EVoid());
#line 506 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Light.es"
return TRUE; ASSERT(FALSE); return TRUE;};