/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

CEntityEvent *EModel3Activate_New(void) { return new EModel3Activate; };
CDLLEntityEvent DLLEvent_EModel3Activate = {
  0x00f20000, &EModel3Activate_New
};
CEntityEvent *EModel3Deactivate_New(void) { return new EModel3Deactivate; };
CDLLEntityEvent DLLEvent_EModel3Deactivate = {
  0x00f20001, &EModel3Deactivate_New
};
CDLLEntityEvent *CModelHolder3_events[] = {
  &DLLEvent_EModel3Deactivate,
  &DLLEvent_EModel3Activate,
};
#define CModelHolder3_eventsct ARRAYCOUNT(CModelHolder3_events)
#define ENTITYCLASS CModelHolder3

CEntityProperty CModelHolder3_properties[] = {
 CEntityProperty(CEntityProperty::EPT_FILENAME, NULL, (0x000000f2<<8)+1, offsetof(CModelHolder3, m_fnModel), "Model file (.smc)", 'M', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FILENAME, NULL, (0x000000f2<<8)+2, offsetof(CModelHolder3, m_fnTexture), "Texture", 'T', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000f2<<8)+3, offsetof(CModelHolder3, m_fStretchAll), "StretchAll", 'S', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ANGLE3D, NULL, (0x000000f2<<8)+4, offsetof(CModelHolder3, m_vStretchXYZ), "StretchXYZ", 'X', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_STRING, NULL, (0x000000f2<<8)+7, offsetof(CModelHolder3, m_strName), "Name", 'N', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_STRING, NULL, (0x000000f2<<8)+12, offsetof(CModelHolder3, m_strDescription), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000f2<<8)+8, offsetof(CModelHolder3, m_bColliding), "Collision", 'L', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_STRING, NULL, (0x000000f2<<8)+9, offsetof(CModelHolder3, m_strModelAnimation), "Model animation (SKA)", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ENUM, &ShadowType_enum, (0x000000f2<<8)+11, offsetof(CModelHolder3, m_stClusterShadows), "Shadows", 'W', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000f2<<8)+13, offsetof(CModelHolder3, m_bBackground), "Background", 'B', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000f2<<8)+21, offsetof(CModelHolder3, m_bTargetable), "Targetable", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ENUM, &CustomShadingType_enum, (0x000000f2<<8)+14, offsetof(CModelHolder3, m_cstCustomShading), "Shading mode", 'H', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ANGLE3D, NULL, (0x000000f2<<8)+15, offsetof(CModelHolder3, m_aShadingDirection), "Shade. Light direction", 'D', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_COLOR, NULL, (0x000000f2<<8)+16, offsetof(CModelHolder3, m_colLight), "Shade. Light color", 'O', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_COLOR, NULL, (0x000000f2<<8)+17, offsetof(CModelHolder3, m_colAmbient), "Shade. Ambient color", 'A', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x000000f2<<8)+18, offsetof(CModelHolder3, m_vShadingDirection), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000f2<<8)+26, offsetof(CModelHolder3, m_bActive), "Active", 0, 0x7F0000FFUL, EPROPF_NETSEND ),
 CEntityProperty(CEntityProperty::EPT_COLOR, NULL, (0x000000f2<<8)+28, offsetof(CModelHolder3, m_colModelColor), "Model Color", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_RANGE, NULL, (0x000000f2<<8)+35, offsetof(CModelHolder3, m_rMipFadeDistMetric), "Mip Fade Dist (Metric)", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000f2<<8)+36, offsetof(CModelHolder3, m_fMipFadeLenMetric), "Mip Fade Len (Metric)", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000f2<<8)+50, offsetof(CModelHolder3, m_bRandomStretch), "Apply RND stretch", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ANGLE3D, NULL, (0x000000f2<<8)+52, offsetof(CModelHolder3, m_fStretchRndXYZ), "Stretch RND XYZ (%)", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000f2<<8)+54, offsetof(CModelHolder3, m_fStretchRndAll), "Stretch RND All (%)", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x000000f2<<8)+55, offsetof(CModelHolder3, m_fStretchRandom), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000000f2<<8)+60, offsetof(CModelHolder3, m_penDestruction), "Destruction", 'Q', C_BLACK  | 0x20, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x000000f2<<8)+61, offsetof(CModelHolder3, m_vDamage), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000f2<<8)+62, offsetof(CModelHolder3, m_tmLastDamage), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000000f2<<8)+63, offsetof(CModelHolder3, m_penDestroyTarget), "Destruction Target", 0, C_WHITE  | 0xFF, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000000f2<<8)+64, offsetof(CModelHolder3, m_penLastDamager), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000f2<<8)+65, offsetof(CModelHolder3, m_tmSpraySpawned), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000f2<<8)+66, offsetof(CModelHolder3, m_fSprayDamage), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000000f2<<8)+67, offsetof(CModelHolder3, m_penSpray), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000f2<<8)+68, offsetof(CModelHolder3, m_fMaxDamageAmmount), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000f2<<8)+70, offsetof(CModelHolder3, m_fClassificationStretch), "Classification stretch", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_COLOR, NULL, (0x000000f2<<8)+80, offsetof(CModelHolder3, m_colBurning), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENUM, &DamageType_enum, (0x000000f2<<8)+90, offsetof(CModelHolder3, m_dmtLastDamageType), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000f2<<8)+91, offsetof(CModelHolder3, m_fChainSawCutDamage), "Chain saw cut dammage", 'C', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000f2<<8)+100, offsetof(CModelHolder3, m_fMaxTessellationLevel), "Max tessellation level", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000f2<<8)+110, offsetof(CModelHolder3, m_bDoNotLoopAnimation), "Animation looping OFF", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000f2<<8)+116, offsetof(CModelHolder3, m_bRenderReflection), "Render reflection?", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000f2<<8)+117, offsetof(CModelHolder3, m_bTerrainShadow), "Terrain Shadow?", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_STRING, NULL, (0x000000f2<<8)+118, offsetof(CModelHolder3, m_strEffectGroupNameEvent), "Model Effect Name(Event)", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000f2<<8)+119, offsetof(CModelHolder3, m_bDecorationObject), "Decoration Object", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000f2<<8)+120, offsetof(CModelHolder3, m_bHasRootTag), "Has __ROOT & __TOP tag", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_STRING, NULL, (0x000000f2<<8)+121, offsetof(CModelHolder3, m_strEffectGroupName), "Model Effect Name", 0, 0x7F0000FFUL, 0),
};
#define CModelHolder3_propertiesct ARRAYCOUNT(CModelHolder3_properties)

CEntityComponent CModelHolder3_components[] = {
#define CLASS_BLOOD_SPRAY ((0x000000f2<<8)+1)
 CEntityComponent(ECT_CLASS, CLASS_BLOOD_SPRAY, 0, "EFNM" "Classes\\BloodSpray.ecl"),
#define EDITOR_AXIS_MODEL ((0x000000f2<<8)+20)
 CEntityComponent(ECT_SKAMODEL, EDITOR_AXIS_MODEL, 0, "EFNM" "Data\\Models\\Editor\\Ska\\Axis.smc"),
};
#define CModelHolder3_componentsct ARRAYCOUNT(CModelHolder3_components)

CEventHandlerEntry CModelHolder3_handlers[] = {
 {0x00f20002, -1, CEntity::pEventHandler(&CModelHolder3::
#line 665 "E:/USA/EntitiesMP/ModelHolder3.es"
Die),DEBUGSTRING("CModelHolder3::Die")},
 {1, -1, CEntity::pEventHandler(&CModelHolder3::
#line 763 "E:/USA/EntitiesMP/ModelHolder3.es"
Main),DEBUGSTRING("CModelHolder3::Main")},
 {0x00f20003, -1, CEntity::pEventHandler(&CModelHolder3::H0x00f20003_Main_01), DEBUGSTRING("CModelHolder3::H0x00f20003_Main_01")},
 {0x00f20004, -1, CEntity::pEventHandler(&CModelHolder3::H0x00f20004_Main_02), DEBUGSTRING("CModelHolder3::H0x00f20004_Main_02")},
};
#define CModelHolder3_handlersct ARRAYCOUNT(CModelHolder3_handlers)

CEntity *CModelHolder3_New(void) { return new CModelHolder3; };
void CModelHolder3_OnInitClass(void) {};
void CModelHolder3_OnEndClass(void) {};
void CModelHolder3_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) {};
void CModelHolder3_OnWorldEnd(CWorld *pwo) {};
void CModelHolder3_OnWorldInit(CWorld *pwo) {};
void CModelHolder3_OnWorldTick(CWorld *pwo) {};
void CModelHolder3_OnWorldRender(CWorld *pwo) {};
ENTITY_CLASSDEFINITION(CModelHolder3, CRationalEntity, "ModelHolder3", "Thumbnails\\ModelHolder3.tbn", 0x000000f2);
DECLARE_CTFILENAME(_fnmCModelHolder3_tbn, "Thumbnails\\ModelHolder3.tbn");
