/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _Pendulum_INCLUDED
#define _Pendulum_INCLUDED 1
extern "C" DECL_DLL CDLLEntityClass CPendulum_DLLClass;
class CPendulum : public CMovableBrushEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
	DECL_DLL virtual void SetDefaultProperties(void);
	CTString m_strName;
	BOOL m_bDynamicShadows;
	FLOAT m_fMaxAngle;
	FLOAT m_fSpeed;
	FLOAT m_fDampFactor;
	FLOAT m_fPendulumFactor;
	FLOAT m_fImpulseFactor;
	FLOAT m_fTriggerImpulse;
	BOOL m_bActive;
   
#line 25 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Pendulum.es"
void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 26 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Pendulum.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 45 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Pendulum.es"
void PostMoving();
#define  STATE_CPendulum_Main 1
	BOOL 
#line 69 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/Pendulum.es"
Main(const CEntityEvent &__eeInput);
	BOOL H0x006a0000_Main_01(const CEntityEvent &__eeInput);
	BOOL H0x006a0001_Main_02(const CEntityEvent &__eeInput);
};
#endif // _Pendulum_INCLUDED
