/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_PointMarker_INCLUDED
#define _EntitiesMP_PointMarker_INCLUDED 1
#include <EntitiesMP/Marker.h>
extern "C" DECL_DLL CDLLEntityClass CPointMarker_DLLClass;
class CPointMarker : public CMarker {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  FLOAT m_fWaitTime;
  RANGE m_fMarkerRange;
  RANGE m_fPatrolAreaInner;
  RANGE m_fPatrolAreaOuter;
  FLOAT m_fPatrolTime;
  enum BoolEType m_betRunToMarker;
  enum BoolEType m_betFly;
  enum BoolEType m_betBlind;
  enum BoolEType m_betDeaf;
  BOOL m_bStartTactics;
   
#line 32 "E:/USA/EntitiesMP/PointMarker.es"
BOOL MovesByTargetedRoute(CTString & strTargetProperty)const;
   
#line 38 "E:/USA/EntitiesMP/PointMarker.es"
BOOL DropsMarker(CTFileName & fnmMarkerClass,CTString & strTargetProperty)const;
   
#line 44 "E:/USA/EntitiesMP/PointMarker.es"
BOOL IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget);
#define  STATE_CPointMarker_Main 1
  BOOL 
#line 53 "E:/USA/EntitiesMP/PointMarker.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_PointMarker_INCLUDED
