/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"

#include "StdH.h"
#include "Common/RestrictedFieldContainer.h"

#include <EntitiesMP/RestrictedField.h>
#include <EntitiesMP/RestrictedField_tables.h>
void CRestrictedField::SetDefaultProperties(void) {
  m_strName = "Restricted Field";
  m_strDescription = "";
  du = 1.0f;
  dv = 1.0f;
  dw = 1.0f;
  iMobCount = 0;
  m_penTarget = NULL;
  m_bActive = TRUE ;
  CRationalEntity::SetDefaultProperties();
}
   CRestrictedField::CRestrictedField(void) 
#line 33 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
{
#line 34 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
InsertRestrictedField  (this );
#line 36 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
}
   CRestrictedField:: ~ CRestrictedField(void) 
#line 41 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
{
#line 42 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
RemoveRestrictedField  (this );
#line 43 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
}
  
#line 45 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
const CTString & CRestrictedField::GetDescription(void)const 
#line 46 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
{
#line 47 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
((CTString &) m_strDescription ) . PrintF  ("-><none>");
#line 48 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
return m_strDescription ;
#line 49 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
}
  
#line 50 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
SLONG CRestrictedField::GetUsedMemory(void) 
#line 51 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
{
#line 52 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
SLONG  slUsedMemory  = sizeof  (CRestrictedField ) - sizeof  (CRationalEntity ) + CRationalEntity  :: GetUsedMemory  ();
#line 53 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
slUsedMemory  += m_strName  . Length  ();
#line 54 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
slUsedMemory  += m_strDescription  . Length  ();
#line 55 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
return slUsedMemory ;
#line 56 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
}
BOOL CRestrictedField::
#line 60 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CRestrictedField_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CRestrictedField::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 63 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
InitAsEditorModel  ();
#line 64 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 65 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 68 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
GetModelObject  () -> StretchModel  (FLOAT3D (du  , dv  , dw ));
#line 69 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
SetModel  (MODEL_DOORCONTROLLER );
#line 70 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
SetModelMainTexture  (TEXTURE_DOORCONTROLLER );
#line 71 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
ModelChangeNotify  ();
#line 72 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
Return(STATE_CURRENT,EVoid());
#line 72 "E:/질산/Korea/Client_USA/EntitiesMP/RestrictedField.es"
return TRUE; ASSERT(FALSE); return TRUE;};