/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

CEntityEvent *ESlaveBaseReconsiderBehavior_New(void) { return new ESlaveBaseReconsiderBehavior; };
CDLLEntityEvent DLLEvent_ESlaveBaseReconsiderBehavior = {
  0x211f0000, &ESlaveBaseReconsiderBehavior_New
};
CEntityEvent *ESlaveFoundNewEnemy_New(void) { return new ESlaveFoundNewEnemy; };
CDLLEntityEvent DLLEvent_ESlaveFoundNewEnemy = {
  0x211f0001, &ESlaveFoundNewEnemy_New
};
CEntityEvent *ESlaveBaseForceWound_New(void) { return new ESlaveBaseForceWound; };
CDLLEntityEvent DLLEvent_ESlaveBaseForceWound = {
  0x211f0002, &ESlaveBaseForceWound_New
};
CEntityEvent *ESlaveBaseDeath_New(void) { return new ESlaveBaseDeath; };
CDLLEntityEvent DLLEvent_ESlaveBaseDeath = {
  0x211f0003, &ESlaveBaseDeath_New
};
CEntityEvent *ESlaveBaseDamage_New(void) { return new ESlaveBaseDamage; };
CDLLEntityEvent DLLEvent_ESlaveBaseDamage = {
  0x211f0004, &ESlaveBaseDamage_New
};
CEntityEvent *ESlaveBaseBlowUp_New(void) { return new ESlaveBaseBlowUp; };
CDLLEntityEvent DLLEvent_ESlaveBaseBlowUp = {
  0x211f0005, &ESlaveBaseBlowUp_New
};
CDLLEntityEvent *CSlaveBase_events[] = {
  &DLLEvent_ESlaveBaseBlowUp,
  &DLLEvent_ESlaveBaseDamage,
  &DLLEvent_ESlaveBaseDeath,
  &DLLEvent_ESlaveBaseForceWound,
  &DLLEvent_ESlaveFoundNewEnemy,
  &DLLEvent_ESlaveBaseReconsiderBehavior,
};
#define CSlaveBase_eventsct ARRAYCOUNT(CSlaveBase_events)
#define ENTITYCLASS CSlaveBase

CEntityProperty CSlaveBase_properties[] = {
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x0000211f<<8)+1, offsetof(CSlaveBase, m_penWatcher), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x0000211f<<8)+2, offsetof(CSlaveBase, m_vStartPosition), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x0000211f<<8)+3, offsetof(CSlaveBase, m_penEnemy), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_STRING, NULL, (0x0000211f<<8)+5, offsetof(CSlaveBase, m_strDescription), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_STRING, NULL, (0x0000211f<<8)+6, offsetof(CSlaveBase, m_strName), "Name", 'N', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_SOUNDOBJECT, NULL, (0x0000211f<<8)+7, offsetof(CSlaveBase, m_soSound), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x0000211f<<8)+8, offsetof(CSlaveBase, m_penOwner), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x0000211f<<8)+43, offsetof(CSlaveBase, m_vDamage), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+44, offsetof(CSlaveBase, m_tmLastDamage), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x0000211f<<8)+46, offsetof(CSlaveBase, m_bRobotBlowup), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+47, offsetof(CSlaveBase, m_fBlowUpSize), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x0000211f<<8)+59, offsetof(CSlaveBase, m_penPathMarker), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x0000211f<<8)+18, offsetof(CSlaveBase, m_vPlayerSpotted), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+58, offsetof(CSlaveBase, m_fRangeLast), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x0000211f<<8)+130, offsetof(CSlaveBase, m_bFadeOut), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+131, offsetof(CSlaveBase, m_fFadeStartTime), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+132, offsetof(CSlaveBase, m_fFadeTime), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x0000211f<<8)+84, offsetof(CSlaveBase, m_penDeathTarget), "Death target", 'D', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ENUM, &EventEType_enum, (0x0000211f<<8)+85, offsetof(CSlaveBase, m_eetDeathType), "Death event type", 'F', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_COLOR, NULL, (0x0000211f<<8)+89, offsetof(CSlaveBase, m_colColor), "Color", 'L', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+92, offsetof(CSlaveBase, m_tmGiveUp), "Give up time", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+93, offsetof(CSlaveBase, m_tmReflexMin), "Reflex Min", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+94, offsetof(CSlaveBase, m_tmReflexMax), "Reflex Max", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+95, offsetof(CSlaveBase, m_fActivityRange), "Activity Range", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x0000211f<<8)+100, offsetof(CSlaveBase, m_bMove), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x0000211f<<8)+120, offsetof(CSlaveBase, m_penMarker), "Marker", 'M', C_RED  | 0xFF, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x0000211f<<8)+140, offsetof(CSlaveBase, m_penMainMusicHolder), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+141, offsetof(CSlaveBase, m_tmLastFussTime), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+145, offsetof(CSlaveBase, m_fSpiritStartTime), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+146, offsetof(CSlaveBase, m_tmSpraySpawned), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+147, offsetof(CSlaveBase, m_fSprayDamage), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x0000211f<<8)+148, offsetof(CSlaveBase, m_penSpray), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+149, offsetof(CSlaveBase, m_fMaxDamageAmmount), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x0000211f<<8)+150, offsetof(CSlaveBase, m_vLastStain), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENUM, &SprayParticlesType_enum, (0x0000211f<<8)+151, offsetof(CSlaveBase, m_sptType), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x0000211f<<8)+163, offsetof(CSlaveBase, m_vTacticsStartPosition), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+167, offsetof(CSlaveBase, m_fTacticVar3), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+168, offsetof(CSlaveBase, m_fTacticVar4), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+169, offsetof(CSlaveBase, m_fTacticVar5), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_COLOR, NULL, (0x0000211f<<8)+180, offsetof(CSlaveBase, m_colBurning), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_INDEX, NULL, (0x0000211f<<8)+194, offsetof(CSlaveBase, m_iSlaveType), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_INDEX, NULL, (0x0000211f<<8)+195, offsetof(CSlaveBase, m_iCurrentCommand), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x0000211f<<8)+201, offsetof(CSlaveBase, m_bMoving), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+205, offsetof(CSlaveBase, m_fAttackStartTime), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+206, offsetof(CSlaveBase, m_fAttackFrequency), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x0000211f<<8)+207, offsetof(CSlaveBase, m_bStop), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x0000211f<<8)+208, offsetof(CSlaveBase, m_fImpactTime), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_INDEX, NULL, (0x0000211f<<8)+214, offsetof(CSlaveBase, m_nAttackCnt), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x0000211f<<8)+215, offsetof(CSlaveBase, m_penKillEnemy), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x0000211f<<8)+216, offsetof(CSlaveBase, m_bPreSkilling), "", 0, 0, 0),
};
#define CSlaveBase_propertiesct ARRAYCOUNT(CSlaveBase_properties)

CEntityComponent CSlaveBase_components[] = {
#define CLASS_WATCHER ((0x0000211f<<8)+1)
 CEntityComponent(ECT_CLASS, CLASS_WATCHER, 0, "EFNM" "Classes\\Watcher.ecl"),
#define CLASS_PROJECTILE ((0x0000211f<<8)+2)
 CEntityComponent(ECT_CLASS, CLASS_PROJECTILE, 0, "EFNM" "Classes\\Projectile.ecl"),
#define CLASS_DEBRIS ((0x0000211f<<8)+3)
 CEntityComponent(ECT_CLASS, CLASS_DEBRIS, 0, "EFNM" "Classes\\Debris.ecl"),
#define CLASS_BASIC_EFFECT ((0x0000211f<<8)+4)
 CEntityComponent(ECT_CLASS, CLASS_BASIC_EFFECT, 0, "EFNM" "Classes\\BasicEffect.ecl"),
#define CLASS_BLOOD_SPRAY ((0x0000211f<<8)+5)
 CEntityComponent(ECT_CLASS, CLASS_BLOOD_SPRAY, 0, "EFNM" "Classes\\BloodSpray.ecl"),
#define MODEL_FLESH ((0x0000211f<<8)+10)
 CEntityComponent(ECT_MODEL, MODEL_FLESH, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Flesh\\Flesh.mdl"),
#define MODEL_FLESH_APPLE ((0x0000211f<<8)+11)
 CEntityComponent(ECT_MODEL, MODEL_FLESH_APPLE, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Fruits\\Apple.mdl"),
#define MODEL_FLESH_BANANA ((0x0000211f<<8)+12)
 CEntityComponent(ECT_MODEL, MODEL_FLESH_BANANA, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Fruits\\Banana.mdl"),
#define MODEL_FLESH_BURGER ((0x0000211f<<8)+13)
 CEntityComponent(ECT_MODEL, MODEL_FLESH_BURGER, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Fruits\\CheeseBurger.mdl"),
#define MODEL_FLESH_LOLLY ((0x0000211f<<8)+14)
 CEntityComponent(ECT_MODEL, MODEL_FLESH_LOLLY, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Fruits\\LollyPop.mdl"),
#define MODEL_FLESH_ORANGE ((0x0000211f<<8)+15)
 CEntityComponent(ECT_MODEL, MODEL_FLESH_ORANGE, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Fruits\\Orange.mdl"),
#define TEXTURE_FLESH_RED ((0x0000211f<<8)+20)
 CEntityComponent(ECT_TEXTURE, TEXTURE_FLESH_RED, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Flesh\\FleshRed.tex"),
#define TEXTURE_FLESH_GREEN ((0x0000211f<<8)+21)
 CEntityComponent(ECT_TEXTURE, TEXTURE_FLESH_GREEN, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Flesh\\FleshGreen.tex"),
#define TEXTURE_FLESH_APPLE ((0x0000211f<<8)+22)
 CEntityComponent(ECT_TEXTURE, TEXTURE_FLESH_APPLE, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Fruits\\Apple.tex"),
#define TEXTURE_FLESH_BANANA ((0x0000211f<<8)+23)
 CEntityComponent(ECT_TEXTURE, TEXTURE_FLESH_BANANA, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Fruits\\Banana.tex"),
#define TEXTURE_FLESH_BURGER ((0x0000211f<<8)+24)
 CEntityComponent(ECT_TEXTURE, TEXTURE_FLESH_BURGER, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Fruits\\CheeseBurger.tex"),
#define TEXTURE_FLESH_LOLLY ((0x0000211f<<8)+25)
 CEntityComponent(ECT_TEXTURE, TEXTURE_FLESH_LOLLY, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Fruits\\LollyPop.tex"),
#define TEXTURE_FLESH_ORANGE ((0x0000211f<<8)+26)
 CEntityComponent(ECT_TEXTURE, TEXTURE_FLESH_ORANGE, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Fruits\\Orange.tex"),
#define MODEL_MACHINE ((0x0000211f<<8)+31)
 CEntityComponent(ECT_MODEL, MODEL_MACHINE, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Stone\\Stone.mdl"),
#define TEXTURE_MACHINE ((0x0000211f<<8)+32)
 CEntityComponent(ECT_TEXTURE, TEXTURE_MACHINE, 0, "EFNM" "Data\\Models\\Effects\\Debris\\Stone\\Stone.tex"),
};
#define CSlaveBase_componentsct ARRAYCOUNT(CSlaveBase_components)

CEventHandlerEntry CSlaveBase_handlers[] = {
 {0x211f0006, -1, CEntity::pEventHandler(&CSlaveBase::
#line 1662 "E:/USA/EntitiesMP/SlaveBase.es"
NewEnemySpotted),DEBUGSTRING("CSlaveBase::NewEnemySpotted")},
 {0x211f0007, -1, CEntity::pEventHandler(&CSlaveBase::
#line 1700 "E:/USA/EntitiesMP/SlaveBase.es"
StopAttack),DEBUGSTRING("CSlaveBase::StopAttack")},
 {0x211f0008, -1, CEntity::pEventHandler(&CSlaveBase::
#line 1719 "E:/USA/EntitiesMP/SlaveBase.es"
InitializeAttack),DEBUGSTRING("CSlaveBase::InitializeAttack")},
 {0x211f0009, -1, CEntity::pEventHandler(&CSlaveBase::
#line 1750 "E:/USA/EntitiesMP/SlaveBase.es"
AttackEnemy),DEBUGSTRING("CSlaveBase::AttackEnemy")},
 {0x211f000a, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f000a_AttackEnemy_01), DEBUGSTRING("CSlaveBase::H0x211f000a_AttackEnemy_01")},
 {0x211f000b, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f000b_AttackEnemy_02), DEBUGSTRING("CSlaveBase::H0x211f000b_AttackEnemy_02")},
 {0x211f000c, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f000c_AttackEnemy_03), DEBUGSTRING("CSlaveBase::H0x211f000c_AttackEnemy_03")},
 {0x211f000d, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f000d_AttackEnemy_04), DEBUGSTRING("CSlaveBase::H0x211f000d_AttackEnemy_04")},
 {0x211f000e, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f000e_AttackEnemy_05), DEBUGSTRING("CSlaveBase::H0x211f000e_AttackEnemy_05")},
 {0x211f000f, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f000f_AttackEnemy_06), DEBUGSTRING("CSlaveBase::H0x211f000f_AttackEnemy_06")},
 {0x211f0010, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0010_AttackEnemy_07), DEBUGSTRING("CSlaveBase::H0x211f0010_AttackEnemy_07")},
 {0x211f0011, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0011_AttackEnemy_08), DEBUGSTRING("CSlaveBase::H0x211f0011_AttackEnemy_08")},
 {0x211f0012, -1, CEntity::pEventHandler(&CSlaveBase::
#line 1773 "E:/USA/EntitiesMP/SlaveBase.es"
PerformAttack),DEBUGSTRING("CSlaveBase::PerformAttack")},
 {0x211f0013, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0013_PerformAttack_01), DEBUGSTRING("CSlaveBase::H0x211f0013_PerformAttack_01")},
 {0x211f0014, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0014_PerformAttack_02), DEBUGSTRING("CSlaveBase::H0x211f0014_PerformAttack_02")},
 {0x211f0015, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0015_PerformAttack_03), DEBUGSTRING("CSlaveBase::H0x211f0015_PerformAttack_03")},
 {0x211f0016, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0016_PerformAttack_04), DEBUGSTRING("CSlaveBase::H0x211f0016_PerformAttack_04")},
 {0x211f0017, -1, CEntity::pEventHandler(&CSlaveBase::
#line 1961 "E:/USA/EntitiesMP/SlaveBase.es"
FireOrHit),DEBUGSTRING("CSlaveBase::FireOrHit")},
 {0x211f0018, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0018_FireOrHit_01), DEBUGSTRING("CSlaveBase::H0x211f0018_FireOrHit_01")},
 {0x211f0019, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0019_FireOrHit_02), DEBUGSTRING("CSlaveBase::H0x211f0019_FireOrHit_02")},
 {0x211f001a, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f001a_FireOrHit_03), DEBUGSTRING("CSlaveBase::H0x211f001a_FireOrHit_03")},
 {0x211f001b, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f001b_FireOrHit_04), DEBUGSTRING("CSlaveBase::H0x211f001b_FireOrHit_04")},
 {0x211f001c, -1, CEntity::pEventHandler(&CSlaveBase::
#line 1995 "E:/USA/EntitiesMP/SlaveBase.es"
Hit),DEBUGSTRING("CSlaveBase::Hit")},
 {0x211f001d, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2001 "E:/USA/EntitiesMP/SlaveBase.es"
Fire),DEBUGSTRING("CSlaveBase::Fire")},
 {0x211f001e, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2015 "E:/USA/EntitiesMP/SlaveBase.es"
BeWounded),DEBUGSTRING("CSlaveBase::BeWounded")},
 {0x211f001f, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2030 "E:/USA/EntitiesMP/SlaveBase.es"
Die),DEBUGSTRING("CSlaveBase::Die")},
 {0x211f0020, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0020_Die_01), DEBUGSTRING("CSlaveBase::H0x211f0020_Die_01")},
 {0x211f0021, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0021_Die_02), DEBUGSTRING("CSlaveBase::H0x211f0021_Die_02")},
 {0x211f0022, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2165 "E:/USA/EntitiesMP/SlaveBase.es"
Death),DEBUGSTRING("CSlaveBase::Death")},
 {0x211f0023, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0023_Death_01), DEBUGSTRING("CSlaveBase::H0x211f0023_Death_01")},
 {0x211f0024, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0024_Death_02), DEBUGSTRING("CSlaveBase::H0x211f0024_Death_02")},
 {0x211f0025, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0025_Death_03), DEBUGSTRING("CSlaveBase::H0x211f0025_Death_03")},
 {0x211f0026, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0026_Death_04), DEBUGSTRING("CSlaveBase::H0x211f0026_Death_04")},
 {0x211f0027, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0027_Death_05), DEBUGSTRING("CSlaveBase::H0x211f0027_Death_05")},
 {0x211f0028, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0028_Death_06), DEBUGSTRING("CSlaveBase::H0x211f0028_Death_06")},
 {0x211f0029, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0029_Death_07), DEBUGSTRING("CSlaveBase::H0x211f0029_Death_07")},
 {0x211f002a, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f002a_Death_08), DEBUGSTRING("CSlaveBase::H0x211f002a_Death_08")},
 {0x211f002b, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f002b_Death_09), DEBUGSTRING("CSlaveBase::H0x211f002b_Death_09")},
 {0x211f002c, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2231 "E:/USA/EntitiesMP/SlaveBase.es"
DeathSequence),DEBUGSTRING("CSlaveBase::DeathSequence")},
 {0x211f002d, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f002d_DeathSequence_01), DEBUGSTRING("CSlaveBase::H0x211f002d_DeathSequence_01")},
 {0x211f002e, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f002e_DeathSequence_02), DEBUGSTRING("CSlaveBase::H0x211f002e_DeathSequence_02")},
 {0x211f002f, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f002f_DeathSequence_03), DEBUGSTRING("CSlaveBase::H0x211f002f_DeathSequence_03")},
 {0x211f0030, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0030_DeathSequence_04), DEBUGSTRING("CSlaveBase::H0x211f0030_DeathSequence_04")},
 {0x211f0031, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0031_DeathSequence_05), DEBUGSTRING("CSlaveBase::H0x211f0031_DeathSequence_05")},
 {0x211f0032, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0032_DeathSequence_06), DEBUGSTRING("CSlaveBase::H0x211f0032_DeathSequence_06")},
 {0x211f0033, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0033_DeathSequence_07), DEBUGSTRING("CSlaveBase::H0x211f0033_DeathSequence_07")},
 {0x211f0034, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0034_DeathSequence_08), DEBUGSTRING("CSlaveBase::H0x211f0034_DeathSequence_08")},
 {0x211f0035, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2281 "E:/USA/EntitiesMP/SlaveBase.es"
Active),DEBUGSTRING("CSlaveBase::Active")},
 {0x211f0036, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0036_Active_01), DEBUGSTRING("CSlaveBase::H0x211f0036_Active_01")},
 {0x211f0037, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0037_Active_02), DEBUGSTRING("CSlaveBase::H0x211f0037_Active_02")},
 {0x211f0038, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2414 "E:/USA/EntitiesMP/SlaveBase.es"
SingleActive),DEBUGSTRING("CSlaveBase::SingleActive")},
 {0x211f0039, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0039_SingleActive_01), DEBUGSTRING("CSlaveBase::H0x211f0039_SingleActive_01")},
 {0x211f003a, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f003a_SingleActive_02), DEBUGSTRING("CSlaveBase::H0x211f003a_SingleActive_02")},
 {0x211f003b, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2561 "E:/USA/EntitiesMP/SlaveBase.es"
Inactive),DEBUGSTRING("CSlaveBase::Inactive")},
 {0x211f003c, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f003c_Inactive_01), DEBUGSTRING("CSlaveBase::H0x211f003c_Inactive_01")},
 {0x211f003d, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f003d_Inactive_02), DEBUGSTRING("CSlaveBase::H0x211f003d_Inactive_02")},
 {0x211f003e, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2635 "E:/USA/EntitiesMP/SlaveBase.es"
SingleInActive),DEBUGSTRING("CSlaveBase::SingleInActive")},
 {0x211f003f, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f003f_SingleInActive_01), DEBUGSTRING("CSlaveBase::H0x211f003f_SingleInActive_01")},
 {0x211f0040, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0040_SingleInActive_02), DEBUGSTRING("CSlaveBase::H0x211f0040_SingleInActive_02")},
 {0x211f0041, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2714 "E:/USA/EntitiesMP/SlaveBase.es"
PreMainLoop),DEBUGSTRING("CSlaveBase::PreMainLoop")},
 {0x211f0042, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2719 "E:/USA/EntitiesMP/SlaveBase.es"
MainLoop_internal),DEBUGSTRING("CSlaveBase::MainLoop_internal")},
 {0x211f0043, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0043_MainLoop_internal_01), DEBUGSTRING("CSlaveBase::H0x211f0043_MainLoop_internal_01")},
 {0x211f0044, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0044_MainLoop_internal_02), DEBUGSTRING("CSlaveBase::H0x211f0044_MainLoop_internal_02")},
 {0x211f0045, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0045_MainLoop_internal_03), DEBUGSTRING("CSlaveBase::H0x211f0045_MainLoop_internal_03")},
 {0x211f0046, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0046_MainLoop_internal_04), DEBUGSTRING("CSlaveBase::H0x211f0046_MainLoop_internal_04")},
 {0x211f0047, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2799 "E:/USA/EntitiesMP/SlaveBase.es"
MainLoop),DEBUGSTRING("CSlaveBase::MainLoop")},
 {0x211f0048, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2809 "E:/USA/EntitiesMP/SlaveBase.es"
StandardBehavior),DEBUGSTRING("CSlaveBase::StandardBehavior")},
 {0x211f0049, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0049_StandardBehavior_01), DEBUGSTRING("CSlaveBase::H0x211f0049_StandardBehavior_01")},
 {0x211f004a, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f004a_StandardBehavior_02), DEBUGSTRING("CSlaveBase::H0x211f004a_StandardBehavior_02")},
 {1, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2915 "E:/USA/EntitiesMP/SlaveBase.es"
Main),DEBUGSTRING("CSlaveBase::Main")},
 {0x211f004b, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2922 "E:/USA/EntitiesMP/SlaveBase.es"
AttackTarget),DEBUGSTRING("CSlaveBase::AttackTarget")},
 {0x211f004c, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2927 "E:/USA/EntitiesMP/SlaveBase.es"
SkillingTarget),DEBUGSTRING("CSlaveBase::SkillingTarget")},
 {0x211f004d, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2932 "E:/USA/EntitiesMP/SlaveBase.es"
SpellSkill),DEBUGSTRING("CSlaveBase::SpellSkill")},
 {0x211f004e, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2937 "E:/USA/EntitiesMP/SlaveBase.es"
StopMovement),DEBUGSTRING("CSlaveBase::StopMovement")},
 {0x211f004f, -1, CEntity::pEventHandler(&CSlaveBase::
#line 2951 "E:/USA/EntitiesMP/SlaveBase.es"
MovetoPoint),DEBUGSTRING("CSlaveBase::MovetoPoint")},
 {0x211f0050, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0050_MovetoPoint_01), DEBUGSTRING("CSlaveBase::H0x211f0050_MovetoPoint_01")},
 {0x211f0051, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0051_MovetoPoint_02), DEBUGSTRING("CSlaveBase::H0x211f0051_MovetoPoint_02")},
 {0x211f0052, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0052_MovetoPoint_03), DEBUGSTRING("CSlaveBase::H0x211f0052_MovetoPoint_03")},
 {0x211f0053, -1, CEntity::pEventHandler(&CSlaveBase::H0x211f0053_MovetoPoint_04), DEBUGSTRING("CSlaveBase::H0x211f0053_MovetoPoint_04")},
};
#define CSlaveBase_handlersct ARRAYCOUNT(CSlaveBase_handlers)

CEntity *CSlaveBase_New(void) { return new CSlaveBase; };
void CSlaveBase_OnInitClass(void) {};
void CSlaveBase_OnEndClass(void) {};
void CSlaveBase_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) {};
void CSlaveBase_OnWorldEnd(CWorld *pwo) {};
void CSlaveBase_OnWorldInit(CWorld *pwo) {};
void CSlaveBase_OnWorldTick(CWorld *pwo) {};
void CSlaveBase_OnWorldRender(CWorld *pwo) {};
ENTITY_CLASSDEFINITION(CSlaveBase, CUnit, "Slave Base", "", 0x0000211f);
DECLARE_CTFILENAME(_fnmCSlaveBase_tbn, "");
