/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"

#include "StdH.h"

#include <TacticsHolder.h>
#include <TacticsHolder_tables.h>
void CTacticsHolder::SetDefaultProperties(void) {
	m_strName = "TacticsHolder";
	m_strDescription = "";
	m_tctType = TCT_NONE ;
	m_fParam1 = 0.0f;
	m_fParam2 = 0.0f;
	m_fParam3 = 0.0f;
	m_fParam4 = 0.0f;
	m_fParam5 = 0.0f;
	m_tmLastActivation = 0.0f;
	CRationalEntity::SetDefaultProperties();
}

#line 39 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
const CTString & CTacticsHolder::GetDescription(void)const {
#line 40 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
return m_strDescription ;
#line 41 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
}
BOOL CTacticsHolder::
#line 44 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CTacticsHolder_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CTacticsHolder::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 46 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
InitAsEditorModel  ();
#line 47 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 48 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 51 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
SetModel  (MODEL_MANAGER );
#line 52 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
SetModelMainTexture  (TEXTURE_MANAGER );
#line 54 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
Jump(STATE_CURRENT,0x00eb0004, FALSE, EInternal());return TRUE;}BOOL CTacticsHolder::H0x00eb0004_Main_05(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00eb0004
if(!(TRUE )){ Jump(STATE_CURRENT,0x00eb0005, FALSE, EInternal());return TRUE;}
#line 55 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x00eb0000, FALSE, EBegin());return TRUE;}BOOL CTacticsHolder::H0x00eb0000_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00eb0000
switch(__eeInput.ee_slEvent)
#line 56 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
{case(EVENTCODE_ETrigger):{const ETrigger&e= (ETrigger&)__eeInput;

#line 58 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
m_tmLastActivation  = _pTimer  -> CurrentTick  ();
#line 59 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
UnsetTimer();Jump(STATE_CURRENT,0x00eb0001, FALSE, EInternal());return TRUE;
#line 60 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
}ASSERT(FALSE);break;default:{
#line 62 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
return TRUE;
#line 63 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
}ASSERT(FALSE);break;
#line 64 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
}return TRUE;}BOOL CTacticsHolder::H0x00eb0001_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00eb0001
;
#line 67 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
SetTimerAfter(0.1f);
Jump(STATE_CURRENT, 0x00eb0002, FALSE, EBegin());return TRUE;}BOOL CTacticsHolder::H0x00eb0002_Main_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00eb0002
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x00eb0003, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CTacticsHolder::H0x00eb0003_Main_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00eb0003
;Jump(STATE_CURRENT,0x00eb0004, FALSE, EInternal());return TRUE;
#line 68 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TacticsHolder.es"
}BOOL CTacticsHolder::H0x00eb0005_Main_06(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00eb0005
 ASSERT(FALSE); return TRUE;};