/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _TextFXHolder_INCLUDED
#define _TextFXHolder_INCLUDED 1
extern "C" DECL_DLL CDLLEntityClass CTextFXHolder_DLLClass;
class CTextFXHolder : public CRationalEntity {
public:
virtual BOOL IsTargetable(void) const { return TRUE; };
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsImportant(void) const { return TRUE; };
	DECL_DLL virtual void SetDefaultProperties(void);
	CTString m_strName;
	CTString m_strDescription;
	CTFileName m_fnmMessage;
	FLOAT m_tmFadeInStart;
	FLOAT m_tmFadeOutStart;
	FLOAT m_tmFadeInLen;
	FLOAT m_tmFadeOutLen;
	FLOAT m_tmAutoFadeOut;
	BOOL m_bDataError;
BOOL bDataLoaded;
   
#line 39 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TextFXHolder.es"
const CTString & GetDescription(void)const;
    CTextFXHolder(void);
   
#line 49 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TextFXHolder.es"
BOOL ReloadData(void);
   
#line 60 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TextFXHolder.es"
BOOL LoadOneFile(const CTFileName & fnm);
   
#line 98 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TextFXHolder.es"
BOOL Text_On(CTFileName fnText);
   
#line 105 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TextFXHolder.es"
void Text_Off(void);
   
#line 111 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TextFXHolder.es"
FLOAT TextFX_Render(CTextFXHolder * penThis,CDrawPort * pdp);
#define  STATE_CTextFXHolder_Main 1
	BOOL 
#line 174 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TextFXHolder.es"
Main(const CEntityEvent &__eeInput);
	BOOL H0x00ef0000_Main_01(const CEntityEvent &__eeInput);
	BOOL H0x00ef0001_Main_02(const CEntityEvent &__eeInput);
	BOOL H0x00ef0002_Main_03(const CEntityEvent &__eeInput);
	BOOL H0x00ef0003_Main_04(const CEntityEvent &__eeInput);
#define  STATE_CTextFXHolder_WaitAndFadeOut 0x00ef0004
	BOOL 
#line 229 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TextFXHolder.es"
WaitAndFadeOut(const CEntityEvent &__eeInput);
	BOOL H0x00ef0005_WaitAndFadeOut_01(const CEntityEvent &__eeInput);
	BOOL H0x00ef0006_WaitAndFadeOut_02(const CEntityEvent &__eeInput);
#define  STATE_CTextFXHolder_ApplyFadeOut 0x00ef0007
	BOOL 
#line 235 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TextFXHolder.es"
ApplyFadeOut(const CEntityEvent &__eeInput);
	BOOL H0x00ef0008_ApplyFadeOut_01(const CEntityEvent &__eeInput);
	BOOL H0x00ef0009_ApplyFadeOut_02(const CEntityEvent &__eeInput);
	BOOL H0x00ef000a_ApplyFadeOut_03(const CEntityEvent &__eeInput);
};
#endif // _TextFXHolder_INCLUDED
