/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"

#include "StdH.h"

#include <TimeController.h>
#include <TimeController_tables.h>
void CTimeController::SetDefaultProperties(void) {
	m_fTimeStretch = 1.0f;
	m_tmFadeIn = 0.25f;
	m_tmInterval = -1.0f;
	m_bAbsolute = TRUE ;
	m_fMyTimer = 0.0f;
	m_tmStretchChangeStart = 0.0f;
	m_strName = "Time controller";
	m_fOldTimeStretch = 0.0f;
	m_fNewTimeStretch = 0.0f;
	CRationalEntity::SetDefaultProperties();
}
BOOL CTimeController::
#line 30 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CTimeController_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CTimeController::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 33 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
InitAsEditorModel  ();
#line 34 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 35 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 38 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
SetModel  (MODEL_TIME_CONTROLLER );
#line 39 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
SetModelMainTexture  (TEXTURE_TIME_CONTROLLER );
#line 42 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
SetTimerAfter(0.1f);
Jump(STATE_CURRENT, 0x02650000, FALSE, EBegin());return TRUE;}BOOL CTimeController::H0x02650000_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x02650000
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x02650001, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CTimeController::H0x02650001_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02650001
;
#line 44 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x02650002, FALSE, EBegin());return TRUE;}BOOL CTimeController::H0x02650002_Main_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x02650002
switch(__eeInput.ee_slEvent)
#line 45 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
{case(EVENTCODE_EBegin):
#line 47 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
{const EBegin&e= (EBegin&)__eeInput;

#line 48 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
return TRUE;
#line 49 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStart):
#line 52 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
{const EStart&eStart= (EStart&)__eeInput;

#line 53 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
m_fOldTimeStretch  = _pNetwork  -> GetRealTimeFactor  ();
#line 54 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
m_fNewTimeStretch  = m_fTimeStretch ;
#line 55 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
Call(STATE_CURRENT, STATE_CTimeController_ApplyTimeStretch, TRUE, EVoid());return TRUE;
#line 56 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
return TRUE;
#line 57 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):
#line 59 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
{const EStop&e= (EStop&)__eeInput;

#line 60 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
_pNetwork  -> SetRealTimeFactor  (1.0f);
#line 61 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
return TRUE;
#line 62 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
}ASSERT(FALSE);break;case(EVENTCODE_EReturn):
#line 64 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
{const EReturn&e= (EReturn&)__eeInput;

#line 65 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
return TRUE;
#line 66 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 67 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
}return TRUE;}BOOL CTimeController::H0x02650003_Main_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02650003
 ASSERT(FALSE); return TRUE;};BOOL CTimeController::
#line 70 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
ChangeTimeStretch(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CTimeController_ChangeTimeStretch
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CTimeController::ChangeTimeStretch expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 72 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
m_fMyTimer  = 0.0f;
#line 73 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
Jump(STATE_CURRENT,0x02650007, FALSE, EInternal());return TRUE;}BOOL CTimeController::H0x02650007_ChangeTimeStretch_03(const CEntityEvent &__eeInput)
#line 74 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02650007
if(!(m_fMyTimer  < m_tmFadeIn  - _pTimer  -> TickQuantum  / 2.0f)){ Jump(STATE_CURRENT,0x02650008, FALSE, EInternal());return TRUE;}
#line 75 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
SetTimerAfter(_pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x02650005, FALSE, EBegin());return TRUE;}BOOL CTimeController::H0x02650005_ChangeTimeStretch_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x02650005
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x02650006, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CTimeController::H0x02650006_ChangeTimeStretch_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02650006
;
#line 76 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
m_fMyTimer  += _pTimer  -> TickQuantum  / _pNetwork  -> GetRealTimeFactor  ();
#line 77 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
FLOAT fNewStretch  = Lerp  (m_fOldTimeStretch  , m_fNewTimeStretch  , Clamp  (m_fMyTimer  / m_tmFadeIn  , 0.0f , 1.0f));
#line 79 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
if(_pNetwork  -> ga_bDemoPlay ){
#line 80 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
_pNetwork  -> ga_fDemoRealTimeFactor  = fNewStretch ;
#line 81 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
}else {
#line 82 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
_pNetwork  -> SetRealTimeFactor  (fNewStretch );
#line 83 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
}Jump(STATE_CURRENT,0x02650007, FALSE, EInternal());return TRUE;
#line 84 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
}BOOL CTimeController::H0x02650008_ChangeTimeStretch_04(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02650008

#line 85 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
if(_pNetwork  -> ga_bDemoPlay ){
#line 86 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
_pNetwork  -> ga_fDemoRealTimeFactor  = m_fNewTimeStretch ;
#line 87 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
}else {
#line 88 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
_pNetwork  -> SetRealTimeFactor  (m_fNewTimeStretch );
#line 89 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
}
#line 90 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
Return(STATE_CURRENT,EReturn  ());
#line 90 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CTimeController::
#line 93 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
ApplyTimeStretch(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CTimeController_ApplyTimeStretch
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CTimeController::ApplyTimeStretch expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 95 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
STATE_CTimeController_ChangeTimeStretch, TRUE;
Jump(STATE_CURRENT, 0x0265000a, FALSE, EBegin());return TRUE;}BOOL CTimeController::H0x0265000a_ApplyTimeStretch_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0265000a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CTimeController_ChangeTimeStretch, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x0265000b, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CTimeController::H0x0265000b_ApplyTimeStretch_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x0265000b
const EReturn&__e= (EReturn&)__eeInput;
;
#line 96 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
if(!(m_tmInterval  > 0)){ Jump(STATE_CURRENT,0x02650010, FALSE, EInternal());return TRUE;}
#line 98 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
SetTimerAfter(m_tmInterval );
Jump(STATE_CURRENT, 0x0265000c, FALSE, EBegin());return TRUE;}BOOL CTimeController::H0x0265000c_ApplyTimeStretch_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0265000c
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0265000d, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CTimeController::H0x0265000d_ApplyTimeStretch_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0265000d
;
#line 99 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
STATE_CTimeController_ResetTimeStretch, TRUE;
Jump(STATE_CURRENT, 0x0265000e, FALSE, EBegin());return TRUE;}BOOL CTimeController::H0x0265000e_ApplyTimeStretch_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0265000e
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CTimeController_ResetTimeStretch, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x0265000f, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CTimeController::H0x0265000f_ApplyTimeStretch_06(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x0265000f
const EReturn&__e= (EReturn&)__eeInput;
;Jump(STATE_CURRENT,0x02650010, FALSE, EInternal());return TRUE;}BOOL CTimeController::H0x02650010_ApplyTimeStretch_07(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02650010

#line 101 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
Return(STATE_CURRENT,EReturn  ());
#line 101 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CTimeController::
#line 104 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
ResetTimeStretch(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CTimeController_ResetTimeStretch
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CTimeController::ResetTimeStretch expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 106 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
if(_pNetwork  -> GetRealTimeFactor  () == 1){Return(STATE_CURRENT,EReturn  ());return TRUE;};
#line 107 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
m_fOldTimeStretch  = _pNetwork  -> GetRealTimeFactor  ();
#line 108 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
m_fNewTimeStretch  = 1.0f;
#line 109 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
STATE_CTimeController_ChangeTimeStretch, TRUE;
Jump(STATE_CURRENT, 0x02650012, FALSE, EBegin());return TRUE;}BOOL CTimeController::H0x02650012_ResetTimeStretch_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x02650012
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CTimeController_ChangeTimeStretch, TRUE, EVoid  ());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x02650013, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CTimeController::H0x02650013_ResetTimeStretch_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x02650013
const EReturn&__e= (EReturn&)__eeInput;
;
#line 110 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
Return(STATE_CURRENT,EReturn  ());
#line 110 "C:/Users/pwesty/Desktop/SD-Source/nov-source/Reco_Csrc/EntitiesMP/TimeController.es"
return TRUE; ASSERT(FALSE); return TRUE;};