/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"

#include "StdH.h"

#include <EntitiesMP/WorldLink.h>
#include <EntitiesMP/WorldLink_tables.h>
void CWorldLink::SetDefaultProperties(void) {
  m_strGroup = "";
  m_strWorld = "";
  m_bStoreWorld = FALSE ;
  m_EwltType = WLT_FIXED ;
  CMarker::SetDefaultProperties();
}
  
#line 34 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
BOOL CWorldLink::HandleEvent(const CEntityEvent & ee) {
#line 35 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
if(ee  . ee_slEvent  == EVENTCODE_ETrigger ){
#line 36 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
ETrigger  & eTrigger  = (ETrigger  &) ee ;
#line 37 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
_SwcWorldChange  . strGroup  = m_strGroup ;
#line 38 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
_SwcWorldChange  . plLink  = GetPlacement  ();
#line 39 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
_SwcWorldChange  . iType  = (INDEX) m_EwltType ;
#line 40 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
_pNetwork  -> ChangeLevel  (m_strWorld  , m_bStoreWorld  , 0);
#line 41 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
return TRUE ;
#line 42 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
}
#line 43 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
return FALSE ;
#line 44 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
}
BOOL CWorldLink::
#line 50 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWorldLink_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWorldLink::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 51 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
InitAsEditorModel  ();
#line 52 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 53 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 56 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
SetModel  (MODEL_WORLDLINK );
#line 57 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
SetModelMainTexture  (TEXTURE_WORLDLINK );
#line 60 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
m_strName  . PrintF  ("World link - %s" , m_strGroup );
#line 62 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
Return(STATE_CURRENT,EVoid());
#line 62 "E:/질산/Korea/Client_USA/EntitiesMP/WorldLink.es"
return TRUE; ASSERT(FALSE); return TRUE;};